### ISSUE TITLE
Flashing firmware using esp-flash-tools_3.6.4

### ISSUE THREAD

**Issue by KrrishnaShah** [espressif/ESP8266_RTOS_SDK#199]
Hello every one,

I'm using virtual_box - eclipse ide - ESP8266_RTOS_SDK.
I've recently updated my sdk with v2.0.0. I've esp8266MOD with 4MB flash.

how can i flash my device using efp-flash-tools v_3.6.4? 

I used to flash esp8266 with previous version like this:
![flash settings and which files where](https://user-images.githubusercontent.com/13435158/40701266-105c846e-63fd-11e8-9d35-17ea09ddad0e.JPG)

I tried the same but the program fail to run.
Can any body help me with this ....

**Comment by 27-301** [comment]
Can you describe the failure more detailed when you use esp-flash-tools v_3.6.4? Can you use old tool to flash your new firmware based on SDK 2.0.0? Can you use the new tool to flash your old firmware?

**Comment by KrrishnaShah** [comment]
I'm using this to flash my esp8266

![flash](https://user-images.githubusercontent.com/13435158/40702500-d31b62f0-6401-11e8-8626-491633016c0b.JPG)

output:
![serial out](https://user-images.githubusercontent.com/13435158/40702512-dc8072c2-6401-11e8-933c-94997fe50a21.JPG)

**Comment by 27-301** [comment]
Maybe it's not related to the download tool, from your log, it's already boot up.

Seems that you don't use the original SDK, since you use rboot as bootloader, can you use examples in SDK and espressif boot to do the test?

Since your blinky.bin starts from 0x2000, do you modify the ld file? From you crash info, your PC is 0x40201d74, which means the address in flash is 0x1d74, but 0x1000~0x2000 in your system is blank_config.bin, not your firmware.

Do you use master branch? or just release version?

**Comment by KrrishnaShah** [comment]
sry for previous 

now i'm using following boot-loader 
but still fails

![image](https://user-images.githubusercontent.com/13435158/40704050-d8e9927e-6406-11e8-8a62-580bc2f25bd3.png)

![image](https://user-images.githubusercontent.com/13435158/40704259-54bacfe4-6407-11e8-9cde-6e903f44656b.png)

**Comment by KrrishnaShah** [comment]
Thanks @27-301 for guiding me through this.

The problem is solved when I untick the DoNotChgBin.
