### ISSUE TITLE
aws iot  error

### ISSUE THREAD

**Issue by myzhang001** [espressif/ESP8266_RTOS_SDK#482]
I (8727) subpub: Connecting to AWS...                                           
E (11487) esp-tls: mbedtls_ssl_handshake returned -0x2700                       
I (11487) esp-tls: Failed to verify peer certificate!                           
I (11487) esp-tls: verification info:   ! The certificate is not correctly signA
                                                                                
E (11517) esp-tls: Failed to open new connection

**Comment by supreetd21** [comment]
0x2700 -  Root CA Error
Since October, Amazon has changed it's root CA from VeriSign to Amazon. You can confirm this by checking "ats"(Amazon Trust Services) in your URL. So, you will have to use the latest certificates from Amazon from here.
https://docs.aws.amazon.com/iot/latest/developerguide/managing-device-certs.html

Use this certificate in your certs/aws-root-ca.pem for RSA-2048: https://www.amazontrust.com/repository/AmazonRootCA1.pem

**Comment by FayeY** [comment]
Hi @myzhang001 , did the above suggestion help you resolve the issue?
