### ISSUE TITLE
Some question about smartconfig (GIT8266O-210)

### ISSUE THREAD

**Issue by metadata1984** [espressif/ESP8266_RTOS_SDK#647]
hardware :esp8266
rtos SDK version : v2.x.x
smartconfig type: airkiss

The Comment of function smartconfig_start say that <Don't call any other APIs during SmartConfig, please call smartconfig_stop first.>

Could anybody tell me that "any other APIs" means？
GPIO apis？should i disable uart or andy other Interrupts ？any network apis？flash apis ？ freertos apis？

i am makeing  a product using esp8266。

There is some freertos's task still working when I call smartconfig_start 。Showld I stop the all other task during smartconfig

**Comment by donghengqaz** [comment]
1. this information tells you may not do other opeartion when smartconfig is work, because they may affect it speed
2. smartconfig costs most of CPU, so you had better stop it before doing other operation.
3. most function like GPIO, UART, FreeRTOS may works, but some functions like Wi-Fi, socket and so on does not
