### ISSUE TITLE
mbedtls_ssl_handshake return -0x5180 (GIT8266O-376)

### ISSUE THREAD

**Issue by Vbansal1996** [espressif/ESP8266_RTOS_SDK#806]
Hardware description - nodemcu 12E module

Problem:
I am trying to make **GET** request to the https url. I am connected to WPA2 Enterprise network.
When ever I tried to make the connection with the host url I am getting this error.

![Screenshot from 2020-01-07 17-34-56](https://user-images.githubusercontent.com/35801637/71894475-5b8a9e80-3174-11ea-9aa4-4aa78b0c3d37.png)

I am not able to Identify the error reason, or meaning of this error.
This error value is not even listed in ssl.h file.

Can I get any help in this.

**Comment by francescolavra** [comment]
The -0x5180 error code corresponds to MBEDTLS_ERR_MD_ALLOC_FAILED, i.e. you are running out of heap space.
If you are using the master or release/v3.3 branches of the SDK code, please make sure to pull the latest commits, since there was a bug (which got fixed in commit https://github.com/espressif/ESP8266_RTOS_SDK/commit/e0b73761b947449b2cce192e8b1dce14ac2d61ca) that in my case was causing the same MBEDTLS_ERR_MD_ALLOC_FAILED error even when there actually was enough free space in the heap. If you are not using the master or release/v3.3 branches, or if you still get the same error after pulling the latest commits, then you are really running out of heap space.

**Comment by Vbansal1996** [comment]
I am using master and using the latest commited SDK in master, and I am getting this issue.

There is any way to resolve this issue?

**Comment by francescolavra** [comment]
You could try to decrease the TLS maximum incoming fragment length option value with `make menuconfig`: go to `> Component config > mbedTLS > TLS maximum incoming fragment length` and change the value from the default 16384 to, say, 8192. This of course works only if your server doesn't send TLS fragments larger than 8192 bytes.

**Comment by Vbansal1996** [comment]
ok Thanks I will check and update.

**Comment by Vbansal1996** [comment]
I make the changes and not getting the error but now It is giving me the 502 bad gateway issue

**Comment by Vbansal1996** [comment]
Thanks for your help I am able to resolve the issue.

**Comment by XingYu2535** [comment]
> You could try to decrease the TLS maximum incoming fragment length option value with `make menuconfig`: go to `> Component config > mbedTLS > TLS maximum incoming fragment length` and change the value from the default 16384 to, say, 8192. This of course works only if your server doesn't send TLS fragments larger than 8192 bytes.

Thanks!!
